//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Input/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""ea903c21-1293-44f4-bb3b-015e01366d10"",
            ""actions"": [
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""Value"",
                    ""id"": ""7da9faad-43ec-4423-af9b-a296bf5daa78"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""79ac28ad-4f7d-4efd-b8e0-4ad079ec15e4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraRotateAxis"",
                    ""type"": ""Value"",
                    ""id"": ""cd503423-a4ed-4656-bc3c-1a8754c53b8f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraRotateToggleMouse"",
                    ""type"": ""Button"",
                    ""id"": ""17005148-0fc2-481c-875f-427ff12da917"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""0e51927f-6dbc-4701-9892-cfa07be50e5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnitPositionPreview"",
                    ""type"": ""Button"",
                    ""id"": ""b2baeb72-01d3-475c-851e-31914d34977b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddSelect"",
                    ""type"": ""Button"",
                    ""id"": ""11d57712-5c8d-46dd-9cfb-da6256523621"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeselectAll"",
                    ""type"": ""Button"",
                    ""id"": ""a713237e-b9a5-427c-8981-49984dfc0ef4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PositionUnit"",
                    ""type"": ""Button"",
                    ""id"": ""af6d402c-7891-4252-880d-657b395fd29a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""MainMovementAxisCamera"",
                    ""id"": ""ca54d26f-b6b0-407a-80ea-69c4bbc322e0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5a52de8c-d59c-49da-bf72-9bdcba856e7f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""056f5bf9-a3e9-4427-824f-b67bbfa2eed7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6a9eec7b-6a35-4311-8798-a6f228365c96"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""82092b62-3463-4d44-a182-631cccb45af3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AlternativeMovementAxisCamera"",
                    ""id"": ""dfef05dd-e3ca-4965-a525-40234516953c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5f4ef025-3637-4fca-8614-33183b40639d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c5d85520-4a46-4134-a0ff-b951b4ac3437"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5b142ee5-a08b-42b4-af69-247b2bb0e1e0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3a0c898c-c516-42ef-8441-5205fa17a8fb"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MainCameraZoom"",
                    ""id"": ""6ae72af6-0c64-4b0f-b857-02b95e249dde"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2a1a3708-609b-41eb-bc3a-f46572ca4d89"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.5)"",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""144e38cd-eb01-4f5a-848d-78982531f8d5"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.5)"",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AlternativeCameraZoom"",
                    ""id"": ""6c3087d2-14c2-46f8-b05c-d385217cf2fd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""9807152a-0c49-4a0a-8f37-8e2256168720"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""b4abc5ee-7fc5-4a7a-a79b-9faf71ea2db0"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""51e6981e-4f1c-4fd4-828d-a96e0174f751"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e242d0ee-173f-4e0a-998c-13c7be3a968d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraRotateAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2e66224c-8592-4f87-a75c-547f79879920"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraRotateAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ab34df98-5702-498f-a601-dc8e471626e5"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraRotateToggleMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81e47191-9d59-4db9-9542-9b1aa77e551d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c66aac5e-3804-4cf7-8432-9810e76035d5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""UnitPositionPreview"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e03f815c-d7c1-418d-9279-d4fe8404bfa2"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""AddSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""130f76b7-ac3d-4885-bad5-f83ecdadc988"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""DeselectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54775677-bd94-4041-b0ad-4a21cc5415a6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""PositionUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard+Mouse"",
            ""bindingGroup"": ""Keyboard+Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_CameraMovement = m_Main.FindAction("CameraMovement", throwIfNotFound: true);
        m_Main_CameraZoom = m_Main.FindAction("CameraZoom", throwIfNotFound: true);
        m_Main_CameraRotateAxis = m_Main.FindAction("CameraRotateAxis", throwIfNotFound: true);
        m_Main_CameraRotateToggleMouse = m_Main.FindAction("CameraRotateToggleMouse", throwIfNotFound: true);
        m_Main_Select = m_Main.FindAction("Select", throwIfNotFound: true);
        m_Main_UnitPositionPreview = m_Main.FindAction("UnitPositionPreview", throwIfNotFound: true);
        m_Main_AddSelect = m_Main.FindAction("AddSelect", throwIfNotFound: true);
        m_Main_DeselectAll = m_Main.FindAction("DeselectAll", throwIfNotFound: true);
        m_Main_PositionUnit = m_Main.FindAction("PositionUnit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
    private readonly InputAction m_Main_CameraMovement;
    private readonly InputAction m_Main_CameraZoom;
    private readonly InputAction m_Main_CameraRotateAxis;
    private readonly InputAction m_Main_CameraRotateToggleMouse;
    private readonly InputAction m_Main_Select;
    private readonly InputAction m_Main_UnitPositionPreview;
    private readonly InputAction m_Main_AddSelect;
    private readonly InputAction m_Main_DeselectAll;
    private readonly InputAction m_Main_PositionUnit;
    public struct MainActions
    {
        private @NewControls m_Wrapper;
        public MainActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraMovement => m_Wrapper.m_Main_CameraMovement;
        public InputAction @CameraZoom => m_Wrapper.m_Main_CameraZoom;
        public InputAction @CameraRotateAxis => m_Wrapper.m_Main_CameraRotateAxis;
        public InputAction @CameraRotateToggleMouse => m_Wrapper.m_Main_CameraRotateToggleMouse;
        public InputAction @Select => m_Wrapper.m_Main_Select;
        public InputAction @UnitPositionPreview => m_Wrapper.m_Main_UnitPositionPreview;
        public InputAction @AddSelect => m_Wrapper.m_Main_AddSelect;
        public InputAction @DeselectAll => m_Wrapper.m_Main_DeselectAll;
        public InputAction @PositionUnit => m_Wrapper.m_Main_PositionUnit;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void AddCallbacks(IMainActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
            @CameraMovement.started += instance.OnCameraMovement;
            @CameraMovement.performed += instance.OnCameraMovement;
            @CameraMovement.canceled += instance.OnCameraMovement;
            @CameraZoom.started += instance.OnCameraZoom;
            @CameraZoom.performed += instance.OnCameraZoom;
            @CameraZoom.canceled += instance.OnCameraZoom;
            @CameraRotateAxis.started += instance.OnCameraRotateAxis;
            @CameraRotateAxis.performed += instance.OnCameraRotateAxis;
            @CameraRotateAxis.canceled += instance.OnCameraRotateAxis;
            @CameraRotateToggleMouse.started += instance.OnCameraRotateToggleMouse;
            @CameraRotateToggleMouse.performed += instance.OnCameraRotateToggleMouse;
            @CameraRotateToggleMouse.canceled += instance.OnCameraRotateToggleMouse;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @UnitPositionPreview.started += instance.OnUnitPositionPreview;
            @UnitPositionPreview.performed += instance.OnUnitPositionPreview;
            @UnitPositionPreview.canceled += instance.OnUnitPositionPreview;
            @AddSelect.started += instance.OnAddSelect;
            @AddSelect.performed += instance.OnAddSelect;
            @AddSelect.canceled += instance.OnAddSelect;
            @DeselectAll.started += instance.OnDeselectAll;
            @DeselectAll.performed += instance.OnDeselectAll;
            @DeselectAll.canceled += instance.OnDeselectAll;
            @PositionUnit.started += instance.OnPositionUnit;
            @PositionUnit.performed += instance.OnPositionUnit;
            @PositionUnit.canceled += instance.OnPositionUnit;
        }

        private void UnregisterCallbacks(IMainActions instance)
        {
            @CameraMovement.started -= instance.OnCameraMovement;
            @CameraMovement.performed -= instance.OnCameraMovement;
            @CameraMovement.canceled -= instance.OnCameraMovement;
            @CameraZoom.started -= instance.OnCameraZoom;
            @CameraZoom.performed -= instance.OnCameraZoom;
            @CameraZoom.canceled -= instance.OnCameraZoom;
            @CameraRotateAxis.started -= instance.OnCameraRotateAxis;
            @CameraRotateAxis.performed -= instance.OnCameraRotateAxis;
            @CameraRotateAxis.canceled -= instance.OnCameraRotateAxis;
            @CameraRotateToggleMouse.started -= instance.OnCameraRotateToggleMouse;
            @CameraRotateToggleMouse.performed -= instance.OnCameraRotateToggleMouse;
            @CameraRotateToggleMouse.canceled -= instance.OnCameraRotateToggleMouse;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @UnitPositionPreview.started -= instance.OnUnitPositionPreview;
            @UnitPositionPreview.performed -= instance.OnUnitPositionPreview;
            @UnitPositionPreview.canceled -= instance.OnUnitPositionPreview;
            @AddSelect.started -= instance.OnAddSelect;
            @AddSelect.performed -= instance.OnAddSelect;
            @AddSelect.canceled -= instance.OnAddSelect;
            @DeselectAll.started -= instance.OnDeselectAll;
            @DeselectAll.performed -= instance.OnDeselectAll;
            @DeselectAll.canceled -= instance.OnDeselectAll;
            @PositionUnit.started -= instance.OnPositionUnit;
            @PositionUnit.performed -= instance.OnPositionUnit;
            @PositionUnit.canceled -= instance.OnPositionUnit;
        }

        public void RemoveCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActions @Main => new MainActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard+Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IMainActions
    {
        void OnCameraMovement(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
        void OnCameraRotateAxis(InputAction.CallbackContext context);
        void OnCameraRotateToggleMouse(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnUnitPositionPreview(InputAction.CallbackContext context);
        void OnAddSelect(InputAction.CallbackContext context);
        void OnDeselectAll(InputAction.CallbackContext context);
        void OnPositionUnit(InputAction.CallbackContext context);
    }
}
